name: torcs-cluster

x-torcs-template: &torcs-template
  image: jimiwilson/torcs-server:latest
  shm_size: 512m
  restart: unless-stopped
  volumes:
    - ../practise.xml:/root/.torcs/config/raceman/practise.xml

services:
  torcs_3001: { <<: *torcs-template, container_name: torcs_3001, ports: ["3001:3001/udp"] }
  torcs_3002: { <<: *torcs-template, container_name: torcs_3002, ports: ["3002:3001/udp"] }
  torcs_3003: { <<: *torcs-template, container_name: torcs_3003, ports: ["3003:3001/udp"] }
  torcs_3004: { <<: *torcs-template, container_name: torcs_3004, ports: ["3004:3001/udp"] }
  torcs_3005: { <<: *torcs-template, container_name: torcs_3005, ports: ["3005:3001/udp"] }
  torcs_3006: { <<: *torcs-template, container_name: torcs_3006, ports: ["3006:3001/udp"] }
  torcs_3007: { <<: *torcs-template, container_name: torcs_3007, ports: ["3007:3001/udp"] }
  torcs_3008: { <<: *torcs-template, container_name: torcs_3008, ports: ["3008:3001/udp"] }
  torcs_3009: { <<: *torcs-template, container_name: torcs_3009, ports: ["3009:3001/udp"] }
  torcs_3010: { <<: *torcs-template, container_name: torcs_3010, ports: ["3010:3001/udp"] }
  torcs_3011: { <<: *torcs-template, container_name: torcs_3011, ports: ["3011:3001/udp"] }
  torcs_3012: { <<: *torcs-template, container_name: torcs_3012, ports: ["3012:3001/udp"] }
  torcs_3013: { <<: *torcs-template, container_name: torcs_3013, ports: ["3013:3001/udp"] }
  torcs_3014: { <<: *torcs-template, container_name: torcs_3014, ports: ["3014:3001/udp"] }
  torcs_3015: { <<: *torcs-template, container_name: torcs_3015, ports: ["3015:3001/udp"] }
  torcs_3016: { <<: *torcs-template, container_name: torcs_3016, ports: ["3016:3001/udp"] }
  torcs_3017: { <<: *torcs-template, container_name: torcs_3017, ports: ["3017:3001/udp"] }
  torcs_3018: { <<: *torcs-template, container_name: torcs_3018, ports: ["3018:3001/udp"] }
  torcs_3019: { <<: *torcs-template, container_name: torcs_3019, ports: ["3019:3001/udp"] }
  torcs_3020: { <<: *torcs-template, container_name: torcs_3020, ports: ["3020:3001/udp"] }
  torcs_3021: { <<: *torcs-template, container_name: torcs_3021, ports: ["3021:3001/udp"] }
  torcs_3022: { <<: *torcs-template, container_name: torcs_3022, ports: ["3022:3001/udp"] }
  torcs_3023: { <<: *torcs-template, container_name: torcs_3023, ports: ["3023:3001/udp"] }
  torcs_3024: { <<: *torcs-template, container_name: torcs_3024, ports: ["3024:3001/udp"] }
  torcs_3025: { <<: *torcs-template, container_name: torcs_3025, ports: ["3025:3001/udp"] }
  torcs_3026: { <<: *torcs-template, container_name: torcs_3026, ports: ["3026:3001/udp"] }
  torcs_3027: { <<: *torcs-template, container_name: torcs_3027, ports: ["3027:3001/udp"] }
  torcs_3028: { <<: *torcs-template, container_name: torcs_3028, ports: ["3028:3001/udp"] }
  torcs_3029: { <<: *torcs-template, container_name: torcs_3029, ports: ["3029:3001/udp"] }
  torcs_3030: { <<: *torcs-template, container_name: torcs_3030, ports: ["3030:3001/udp"] }
  torcs_3031: { <<: *torcs-template, container_name: torcs_3031, ports: ["3031:3001/udp"] }
  torcs_3032: { <<: *torcs-template, container_name: torcs_3032, ports: ["3032:3001/udp"] }

  
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.240.0/20