import copy
import math
import gymnasium as gym
import numpy as np

from torcs_client import TorcsClient, launch_torcs

class TorcsEnv(gym.Env):
    # Defining features, their size and scaling factors
    SENSOR_CONFIG = {
        "angle": (1, 3.14159),
        "curLapTime": (1, 1.0),
        "damage": (1, 10000.0),
        "distFromStart": (1, 10000.0),
        "distRaced": (1, 10000.0),
        "focus": (5, 200.0),
        "fuel": (1, 100.0),
        "gear": (1, 6.0),
        "lastLapTime": (1, 1.0),
        "opponents": (36, 200.0),
        "racePos": (1, 1.0),
        "rpm": (1, 10000.0),
        "speedX": (1, 300.0),
        "speedY": (1, 300.0),
        "speedZ": (1, 300.0),
        "track": (19, 200.0),
        "trackPos": (1, 1.0),
        "wheelSpinVel": (4, 100.0),
        "z": (1, 1.0)
    }

    def __init__(self, sensor_features=None, reward_function=None, port: int = 3001):
        super().__init__()

        self.client = None
        self.port = port
        self.time_step = 0
        self.initial_reset = True
        self.reward_function = reward_function or TorcsEnv.calculate_reward

        # Setting default features if none are provided
        if sensor_features is None:
            self.sensor_features = ["speedX", "angle", "trackPos", "track"]
        else:
            self.sensor_features = sensor_features

        # --- ACTION SPACE ---
        # The agent controls 3 things: [Steering, Acceleration]
        # Steering: -1.0 (Right) to 1.0 (Left)
        # Accel:     0.0 (No Gas) to 1.0 (Full Gas)
        # Break:     0.0 (No Break) to 1.0 (Full Break)
        self.action_space = gym.spaces.Box(
            low=np.array([-1.0, 0.0, 0.0]),
            high=np.array([1.0, 1.0, 1.0]),
            dtype=np.float32
        )

        total_dims = sum(self.SENSOR_CONFIG[feat][0] for feat in self.sensor_features)
        self.observation_space = gym.spaces.Box(
            low=-np.inf,
            high=np.inf,
            shape=(total_dims,),
            dtype=np.float32
        )

    def step(self, action):
        # Updating actions with new ones
        self.client.actions.steering = float(action[0])
        self.client.actions.accel = float(action[1])

        # Changing gears and applying ABS if needed
        self.client.actions.gear = self.change_gear(self.client.sensors.gear, self.client.sensors.rpm)

        raw_brake = float(action[2])
        self.client.actions.brake = self.filter_abs(self.client.sensors.speedX, self.client.sensors.wheelSpinVel,
                                                    raw_brake)

        # Sending actions to torcs
        prev_sensors = copy.deepcopy(self.client.sensors)
        self.client.send_action()
        raw_sensors = self.client.get_sensors()

        if raw_sensors is None:
            return np.zeros(self.observation_space.shape), 0.0, True, False, {}

        self.client.sensors.update(raw_sensors)

        # Processing sensors, calculating reward, and checking termination
        observation = self.process_sensors(self.client.sensors)
        terminated = self.is_terminal(self.client.sensors)
        reward = self.reward_function(prev_sensors, self.client.sensors, terminated)

        truncated = self.time_step >= 20000

        self.time_step += 1
        return observation, reward, terminated, truncated, {}

    # Currently HARD RESET as soft doesn't seemly work on windows
    # We relaunch torcs every epoch
    def reset(self, relaunch=False, seed=None, options=None):
        super().reset(seed=seed)
        self.time_step = 0

        if self.client is not None and self.client.sock is not None:
            self.client.sock.close()

        if options is None: launch_torcs()
        self.client = TorcsClient(self.port)
        self.initial_reset = False

        raw_obs = self.client.get_sensors()
        if raw_obs:
            self.client.sensors.update(raw_obs)
        observation = self.process_sensors(self.client.sensors)

        return observation, {}


    # A default reward function generated by granite
    @staticmethod
    def calculate_reward(previous_sensors, current_sensors, terminated) -> float:
        """
        Optimized for absolute fastest lap times on technical tracks.
        Encourages using the full width of the track for apexing corners,
        but harshly punishes leaving the tarmac or taking damage.
        """
        # Extract direct attributes from the Sensor objects
        speed_x = current_sensors.speedX
        angle = current_sensors.angle
        track_pos = current_sensors.trackPos

        curr_damage = current_sensors.damage
        prev_damage = previous_sensors.damage

        # --- 1. Forward Progress ---
        # Reward high speed, but multiply by cos(angle) so the AI only
        # gets points if the car is pointing down the track.
        # Dividing by 100 keeps the reward numbers from exploding at 200km/h.
        progress = (speed_x * math.cos(angle)) / 100.0

        # --- 2. The "Lava" Off-Track Penalty ---
        # Let the AI use the edges of the track for apexing (no penalty inside [-1, 1]).
        # But if it touches the grass/gravel, hit it with a massive penalty.
        if abs(track_pos) > 1.0:
            # The faster you fly off the track, the harder the penalty
            off_track_penalty = 5.0 + (speed_x / 50.0)
        else:
            off_track_penalty = 0.0

        # --- 3. Wrong Way / Spin-out Penalty ---
        # If cos(angle) is negative, the car is facing backward.
        wrong_way_penalty = 0.0
        if math.cos(angle) < 0:
            wrong_way_penalty = 10.0

        # --- 4. Damage Delta Penalty ---
        # Penalize new damage on this specific frame.
        damage_delta = max(0.0, curr_damage - prev_damage)
        damage_penalty = damage_delta * 2.0

        reward = progress - off_track_penalty - wrong_way_penalty - damage_penalty

        if terminated:
            if current_sensors.lastLapTime > 0.0:
                reward += 5000
                print(f"LAP COMPLETE! Time: {current_sensors.lastLapTime}")

            elif abs(current_sensors.trackPos) > 1.0:
                reward -= 100


        return float(reward)

    @staticmethod
    def is_terminal(sensors) -> bool:
        last_lap = sensors.lastLapTime
        current_lap = sensors.curLapTime
        track_pos = sensors.trackPos

        lap_done = last_lap > 0.0 and current_lap < 0.5
        off_track = abs(track_pos) > 1.0

        return bool(lap_done or off_track)

    # Translated gear changing code from: https://computerscience.missouristate.edu/SAIL/_Files/Simulated-Car-Racing-Championship-Competition-Software-Manual.pdf
    @staticmethod
    def change_gear(current_gear: int, rpm: float) -> int:
        # Gear change thresholds
        gear_up = [5000, 6000, 6000, 6500, 7000, 999999]
        gear_down = [0, 2500, 3000, 3000, 3500, 3500]

        if current_gear < 1:
            return 1

        # Changing gears based on RPM
        if current_gear < 6 and rpm >= gear_up[current_gear - 1]:
            return current_gear + 1

        elif current_gear > 1 and rpm <= gear_down[current_gear - 1]:
            return current_gear - 1

        return current_gear

    # Translated abs code from: https://computerscience.missouristate.edu/SAIL/_Files/Simulated-Car-Racing-Championship-Competition-Software-Manual.pdf
    @staticmethod
    def filter_abs(speed_x: float, wheel_spin_vel: list, brake: float) -> float:
        wheel_radius = [0.3306, 0.3306, 0.3276, 0.3276]
        abs_slip = 2.0
        abs_range = 3.0
        abs_min_speed = 3.0

        # Convert car speed from km/h to m/s
        speed_ms = speed_x / 3.6

        # When speed is lower than min speed for ABS, do nothing
        if speed_ms < abs_min_speed:
            return brake

        # Compute the speed of wheels in m/s
        wheel_speed = 0.0
        for i in range(4):
            wheel_speed += wheel_spin_vel[i] * wheel_radius[i]

        # Slip is the difference between actual speed of car and average speed of wheels
        slip = speed_ms - (wheel_speed / 4.0)

        # When slip is too high, apply ABS by reducing the braking force
        if slip > abs_slip:
            brake = brake - (slip - abs_slip) / abs_range

        # Ensure brake does not go below 0
        return max(0.0, brake)


    def process_sensors(self, sensors) -> np.ndarray:
        """
        Converts raw sensor values into a normalised numpy array.
        :param sensors: Sensor object
        :return: normalised sensor values
        """
        sensor_values = []

        for feature in self.sensor_features:
            raw_value = getattr(sensors, feature)
            length, scale = self.SENSOR_CONFIG[feature]

            array = np.atleast_1d(raw_value).astype(np.float32)

            if array.size != length:
                padded_array = np.zeros(length, dtype=np.float32)
                n = min(length, array.size)
                padded_array[:n] = array[:n]
                array = padded_array

            sensor_values.append(array / scale)

        return np.concatenate(sensor_values)
